// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLjgVA6emJe__4iRsvoEKE62QQyArIVkg',
    appId: '1:845038278543:web:b5245da2d121a6ec385dfa',
    messagingSenderId: '845038278543',
    projectId: 'porcamanage',
    authDomain: 'porcamanage.firebaseapp.com',
    storageBucket: 'porcamanage.firebasestorage.app',
    measurementId: 'G-G1LX4ECBCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrXz-GAGKotxPc2f9eKg0QdzdTuDXncqU',
    appId: '1:845038278543:android:cd77add22fc9da8b385dfa',
    messagingSenderId: '845038278543',
    projectId: 'porcamanage',
    storageBucket: 'porcamanage.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQa0_qlSPTUkvNPMHAEOYz70XT3qwzG8s',
    appId: '1:845038278543:ios:04b6d701a90f3119385dfa',
    messagingSenderId: '845038278543',
    projectId: 'porcamanage',
    storageBucket: 'porcamanage.firebasestorage.app',
    iosBundleId: 'com.example.porcamanage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQa0_qlSPTUkvNPMHAEOYz70XT3qwzG8s',
    appId: '1:845038278543:ios:04b6d701a90f3119385dfa',
    messagingSenderId: '845038278543',
    projectId: 'porcamanage',
    storageBucket: 'porcamanage.firebasestorage.app',
    iosBundleId: 'com.example.porcamanage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLjgVA6emJe__4iRsvoEKE62QQyArIVkg',
    appId: '1:845038278543:web:0632f1f06339f9d5385dfa',
    messagingSenderId: '845038278543',
    projectId: 'porcamanage',
    authDomain: 'porcamanage.firebaseapp.com',
    storageBucket: 'porcamanage.firebasestorage.app',
    measurementId: 'G-QXGVVBLFKX',
  );
}
